#define HISTOGRAM_WIDTH   1280
#define HISTOGRAM_HEIGHT  160

#define MAIN_WINDOW_WIDTH   1280
#define MAIN_WINDOW_HEIGHT  720 + HISTOGRAM_HEIGHT

#define CAMERA_FRAME_WIDTH   1280
#define CAMERA_FRAME_HEIGHT  720

#define SPECTRUM_AREA_WIDTH   1280
#define SPECTRUM_AREA_HEIGHT  720


